apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: june18-test-no-db-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june18-test-no-db-3
  name: june18-test-no-db-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
