apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: june18-test-no-db-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june18-test-no-db-3
  name: june18-test-no-db-3
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: june18-test-no-db-3
